services:

   app.form.registration:
       class: CitrespBundle\Form\Security\RegistrationType
       tags:
         - { name: form.type, alias: app_user_registration }

   app.form.profile:
       class: CitrespBundle\Form\Security\ProfileType
       tags:
         - { name: form.type, alias: app_user_profile }

   twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
          - { name: twig.extension }
       debug: true


# Services
# ===========================
   citresp.addOne:
       class: CitrespBundle\Services\AddOne

   citresp.addOneToReportedCount:
       class: CitrespBundle\Services\AddOneToReportedCount
       arguments:
          - "@citresp.addOne"

   citresp.checkUserCity:
       class: CitrespBundle\Services\CheckUserCity

   citresp.citiesNotCreated:
       class: CitrespBundle\Services\CitiesNotCreated

   citresp.createAtlContent:
       class: CitrespBundle\Services\CreateAtlContent

   citresp.googleMapApi:
       class: CitrespBundle\Services\GoogleMapApi

   citresp.HydrateCity:
       class: CitrespBundle\Services\HydrateCity

   citresp.HydrateComment:
       class: CitrespBundle\Services\HydrateComment

   citresp.HydrateReporting:
       class: CitrespBundle\Services\HydrateReporting
       arguments:
          - "@citresp.createAtlContent"

   citresp.NotificationMailer:
       class: CitrespBundle\Services\Mailer
       arguments:
          - "@mailer"
          - "@templating"
          - "%mailer_user%"