services:
   # citresp.example:
   #     class: CitrespBundle\Example
   #     arguments: ["@service_id", "plain_value", "%parameter%"]

   app.form.registration:
       class: CitrespBundle\Form\Security\RegistrationType
       tags:
         - { name: form.type, alias: app_user_registration }

   twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
          - { name: twig.extension }

       debug: true


# Services
# ===========================
   citresp.addOne:
       class: CitrespBundle\Services\AddOne

   citresp.addOneToReportedCount:
       class: CitrespBundle\Services\AddOneToReportedCount
       arguments:
          - "@citresp.addOne"

   citresp.createAtlContent:
       class: CitrespBundle\Services\CreateAtlContent

   citresp.citiesNotCreated:
       class: CitrespBundle\Services\CitiesNotCreated

   citresp.googleMapApi:
       class: CitrespBundle\Services\GoogleMapApi

   citresp.HydrateCity:
       class: CitrespBundle\Services\HydrateCity

   citresp.HydrateComment:
       class: CitrespBundle\Services\HydrateComment

   citresp.HydrateReporting:
       class: CitrespBundle\Services\HydrateReporting
       arguments:
          - "@citresp.createAtlContent"

   # citresp.registrationListener:
   #     class: CitrespBundle\EventListener\RegistrationListener
   #     tags:
   #        - { name: kernel.event_subscriber }
