citresp:
    resource: "@CitrespBundle/Controller/"
    type:     annotation
    prefix:   /


login:
    path: /login

login_check:
    path: /login_check

logout:
    path: /logout

# app:
#     resource: '@AppBundle/Controller/'
#     type: annotation
