citresp:
    resource: "@CitrespBundle/Controller/"
    type:     annotation
    prefix:   /


# login:
#     path: /login
#
# login_check:
#     path: /login_check
#
# logout:
#     path: /logout


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
