# app/config/security.yml
security:
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: bcrypt


    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_MODERATOR, ROLE_CITY]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        # in_memory:
        #     memory:
        #         users:
        #             user: { password: userpass, roles: ['ROLE_USER'] }
        #             moderator: { password: moderatorpass, roles: ['ROLE_MODERATOR'] }
        #             city: { password: citypass, roles: ['ROLE_CYTI'] }
        #             admin: { password: adminpass, roles: ['ROLE_ADMIN'] }


    # provider: in_memory


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            # form_login:
            #     login_path: login
            #     check_path: login_check
            logout: true
                # path: logout
                target: /
            logout_on_user_change: true

            anonymous: true
            remember_me:
                secret: '%secret%' # %secret% est un paramètre de parameter


    access_control:
          #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
